item_configs = {
    "axe": {
        "durability": 30,
        "craft time": 14,
        "consumable": False,
        "price": 30,
        "item type": "logging",
        "stat bonus": 10,
        "craft materials": {"wood": 3, "stone": 3, "water": 2},
        "recycle materials": {"wood": 1, "stone": 1},
    },
    "smithing hammer": {
        "durability": 60,
        "craft time": 28,
        "consumable": False,
        "price": 400,
        "item type": "smithing",
        "stat bonus": 10,
        "craft materials": {"wood": 1, "stone": 2, "water": 3},
        "recycle materials": {"wood": 1, "stone": 2, "water": 0},
    },
    "pickaxe": {
        "durability": 25,
        "craft time": 14,
        "consumable": False,
        "price": 35,
        "item type": "mining",
        "stat bonus": 10,
        "craft materials": {"wood": 5, "stone": 6, "water": 2},
        "recycle materials": {"wood": 2, "stone": 3, "water": 0},
    },
    "sword": {
        "durability": 50,
        "craft time": 22,
        "consumable": False,
        "price": 100,
        "item type": "damage",
        "stat bonus": 20,
        "craft materials": {"wood": 0, "stone": 6, "water": 3},
        "recycle materials": {"wood": 0, "stone": 3, "water": 0},
    },
    "bow": {
        "durability": 50,
        "craft time": 20,
        "consumable": False,
        "price": 95,
        "item type": "damage",
        "stat bonus": 15,
        "craft materials": {"wood": 6, "stone": 0, "water": 3},
        "recycle materials": {"wood": 2, "stone": 0, "water": 0},
    },
    "arrows": {
        "durability": 1,
        "craft time": 5,
        "consumable": True,
        "price": 60,
        "item type": "damage",
        "stat bonus": 5,
        "craft materials": {"wood": 5, "stone": 2, "water": 1},
        "recycle materials": {"wood": 2, "stone": 1, "water": 0},
    },
    "cooking utensils": {
        "durability": 70,
        "craft time": 10,
        "consumable": False,
        "price": 60,
        "item type": "cooking equipment",
        "stat bonus": 10,
        "craft materials": {"wood": 5, "stone": 2, "water": 1},
        "recycle materials": {"wood": 2, "stone": 1, "water": 0},
    },
    "armor": {
        "durability": 200,
        "craft time": 30,
        "consumable": False,
        "price": 150,
        "item type": "armor",
        "stat bonus": 50,
        "craft materials": {"wood": 2, "stone": 7, "water": 3},
        "recycle materials": {"wood": 1, "stone": 3, "water": 0},
    },
    "medical equipment": {
        "durability": 70,
        "craft time": 25,
        "consumable": False,
        "price": 70,
        "item type": "healing equipment",
        "stat bonus": 10,
        "craft materials": {"wood": 2, "stone": 5, "water": 1},
        "recycle materials": {"wood": 1, "stone": 1, "water": 0},
    },
    "bandages": {
        "durability": 1,
        "craft time": 20,
        "consumable": True,
        "price": 35,
        "item type": "healing",
        "stat bonus": 500,
        "craft materials": {"wood": 1, "herbs": 3, "water": 1},
        "recycle materials": {"wood": 1, "stone": 1, "water": 0},
    },
    "food": {
        "durability": 1,
        "craft time": 15,
        "consumable": True,
        "price": 25,
        "item type": "satiation",
        "stat bonus": 500,
        "craft materials": {"wood": 1, "wheat": 3, "water": 1},
        "recycle materials": {"wood": 1, "stone": 1, "water": 0},
    },
    "wood": {
        "durability": 1,
        "craft time": 0,
        "consumable": True,
        "price": 10,
        "item type": "wood",
        "stat bonus": 0,
        "craft materials": {"wood": 1},
        "recycle materials": {"wood": 1},
    },
    "stone": {
        "durability": 1,
        "craft time": 0,
        "consumable": True,
        "price": 10,
        "item type": "stone",
        "stat bonus": 0,
        "craft materials": {"stone": 1},
        "recycle materials": {"stone": 1},
    },
    "wheat": {
        "durability": 1,
        "craft time": 0,
        "consumable": True,
        "price": 10,
        "item type": "wheat",
        "stat bonus": 0,
        "craft materials": {"wheat": 1},
        "recycle materials": {"wheat": 1},
    },
    "water": {
        "durability": 1,
        "craft time": 0,
        "consumable": True,
        "price": 5,
        "item type": "water",
        "stat bonus": 0,
        "craft materials": {"water": 1},
        "recycle materials": {"water": 1},
    },
    "herbs": {
        "durability": 1,
        "craft time": 0,
        "consumable": True,
        "price": 10,
        "item type": "herbs",
        "stat bonus": 0,
        "craft materials": {"herbs": 1},
        "recycle materials": {"herbs": 1},
    },
}
